#!/usr/bin/env bash
# sub-domain creation code for web-servers
obtain_record() {
  local domain="$1"
  local subdomain="$2"

  if [[ -z "$subdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi

  for sub in "${subdomains[@]}"; do
    record_type=$(dig +short "$sub.$domain" | awk '{ if ($0 ~ /^[0-9.]+$/) { print "A" } else { print $1 } }')
    destination=$(dig +short "$sub.$domain" A | awk 'NR==1 {print $1}')
    echo "The subdomain $sub is a $record_type record and points to $destination"
  done
}

obtain_record "$1" "$2"
