#!/usr/bin/bash
# Send to the server from client

if [ $# -lt 3 ]; then
    echo Usage: "0-transer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

fp="$1"
S_IP="$2"
U_name="$3"
ssh_key="$4"

scp -o StrictHostKeyChecking=no -i "$fp" "$S_IP" "$U_name" "$ssh_key"
