#!/usr/bin/env bash
# Install Ubuntu webserver on server and set helloworld

sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

sudo service nginx start # lunch the service

sudo ufw allow 'Nginx HTTP' # allow this protocol

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
