#!/usr/bin/env bash

# Install Nginx
apt-get -y update
apt-get -y install nginx

# running hello
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# creating a redirecting file 
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/AyBims permanent;/" /etc/nginx/sites-available/default

# start service
service nginx start
