#!/usr/bin/env bash

#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
new_string="\\\trewrite ^/redirect_me hhttps://www.youtube.com/watch?v=MjoP9GWgxe0&t=1592s permanent;"
sudo sed -i "19i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
sudo apt update

sudo service nginx start
