#!/usr/bin/env bash
# check if file exist following rules

if [ -a school ];
then
    echo "school file exists"
else
    echo "school file does not exit"
fi
if [ ! -s school ];
then
    echo "school file is empty"
else
    echo "school file is not empty"
fi
if [ -f school ];
then
    echo "school is a regular file"
fi
