#!/usr/bin/bash
# A script for block incoming traffic by firewall

sudo apt update -y
sudo apt upgrade -y
sudo apt-get install ufw

sudo ufw disable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw allow "OpenSSH"

sudo ufw enabe
